### ISSUE TITLE
add netmask and cidr function

### ISSUE THREAD

**Issue by calvin2021y** [jrepp/ipv6-parse#11]
**Is your feature request related to a problem? Please describe.**

need to convert  netmask address `255.255.255.0`,  `ffff:ffff:ffff:ffff::` to cidr.

need convert cidr into netmask address.

**Describe the solution you'd like**

add function to convert from cidr to netmask address, and netmask address to cidr.

**Additional context**

Like to write a tool to parse subnet/netmask/cidr.

**Comment by jrepp** [comment]
Looking at this request. Thank you for submitting it.

**Comment by jrepp** [comment]
Is it your goal to represent CIDR bits in a full address? 192.168.1.1/255.255.255.0 or to simply have a tool that essentially counts the number of set bits? 255.255.255.0 -> /24

I'll have to re-read the spec but I think CIDR notation is in number of bits, although it's often the case that we see "netmasks" in output of tools such as ifconfig etc.

It's likely possible for the parser to detect what type of notation is being used in the CIDR state and provide a conversion. To do a a bare conversion there would have to be another external API which could be shared by the internal parsing code.

**Comment by calvin2021y** [comment]
I am current use some function from https://github.com/sii/sipcalc , I am not sure it should be integrated into ipv6-parse.  if so I can skip the glue code.
