### ISSUE TITLE
not support short ipv4 format 

### ISSUE THREAD

**Issue by calvin2021y** [jrepp/ipv6-parse#5]
```sh
./ipv6-cmd "1.1"
error: IPv4 compatible address was used but required 4 octets, event-code: (5)
    1.1
    1.1
- failed to parse: '1.1'
```

ping, dig, ssh, curl all support "1.1" 

```sh
dig @1.1 fb.com
curl https://1.1
```

**Comment by jrepp** [comment]
I did some testing and this can be supported. There are a few corner cases that need to be accounted for.

e.g.

1 -> 0.0.0.1
1.2 -> 1.0.0.2
1.2.3 -> 1.2.0.3

1:1 -> 0.0.0.1 port 1 (must be differentiated from invalid IPv6 address)

curl often returns error 1003 on my system but ping and dig display the behavior above.

**Comment by jrepp** [comment]
Added.
